   name: C++ CI

   on:
     push:
       branches: [ main ]
     pull_request:
       branches: [ main ]

   jobs:
    build-and-test:
      runs-on: ubuntu-latest
      steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: build application
        run: make FDEBUG=true
      - name: test application
        run: make test FDEBUG=true
